// <auto-generated />
using System;
using Comidas.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comidas.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Comidas.Shared.Entidades.ComidaPersona", b =>
                {
                    b.Property<int>("ComidaRapidaId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("ComidasRapidasId")
                        .HasColumnType("int");

                    b.HasKey("ComidaRapidaId", "PersonaId");

                    b.HasIndex("ComidasRapidasId");

                    b.HasIndex("PersonaId");

                    b.ToTable("ComidasPersonas");
                });

            modelBuilder.Entity("Comidas.Shared.Entidades.ComidasRapidas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComidasRapidas");
                });

            modelBuilder.Entity("Comidas.Shared.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Comidas.Shared.Entidades.ComidaPersona", b =>
                {
                    b.HasOne("Comidas.Shared.Entidades.ComidasRapidas", "ComidasRapidas")
                        .WithMany("ComidaPersonas")
                        .HasForeignKey("ComidasRapidasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comidas.Shared.Entidades.Persona", "Persona")
                        .WithMany("ComidasPersona")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComidasRapidas");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Comidas.Shared.Entidades.ComidasRapidas", b =>
                {
                    b.Navigation("ComidaPersonas");
                });

            modelBuilder.Entity("Comidas.Shared.Entidades.Persona", b =>
                {
                    b.Navigation("ComidasPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
